dist: xenial
language: java

before_install: unset -v _JAVA_OPTIONS
install: true
script: mvn install && (cd tests; mvn verify)

after_failure:
  - cd tests
#  - echo "basic/gradle"
#  - tail -200 target/it/basic/gradle/run-out.log
#  - tail -200 target/it/basic/gradle/run-err.log
  - echo "basic/maven"
  - tail -200 target/it/basic/maven/run-out.log
  - tail -200 target/it/basic/maven/run-err.log
  - cd -

before_cache:
  - rm -rf $HOME/.m2/repository/de/sormuras/junit

cache:
  directories:
  - $HOME/.m2
